# Generated by Django 4.1.1 on 2022-10-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppTwo", "0002_topic_webpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstN", models.CharField(max_length=60)),
                ("lastN", models.CharField(max_length=60, unique=True)),
                ("email", models.CharField(max_length=60, unique=True)),
            ],
        ),
    ]
