# Generated by Django 4.1.1 on 2022-10-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppTwo", "0003_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="email", field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="user", name="lastN", field=models.CharField(max_length=60),
        ),
    ]
