# Generated by Django 4.1.1 on 2022-10-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppTwo", "0004_alter_user_email_alter_user_lastn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webpage", name="name", field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name="webpage", name="url", field=models.URLField(),
        ),
    ]
